#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ANSI_VIEW="$PROJECT_ROOT/projects/ansiview"

if ! "$SCRIPT_DIR/ansiview-lib-current"; then
    echo "ERROR: Failed to update ansiview assetss/lib/."
    exit 1
fi

# Start the file server
echo "Starting file server..."
cd "$ANSI_VIEW"
exec deno run --allow-net --allow-read --allow-sys jsr:@std/http/file-server -v
